language:
  - ruby

rvm:
  - 2.3.1

install:
  - bundle install --jobs=3 --retry=3

before_script:
  - cp config/database.yml.example config/database.yml
  - rm .rspec
  - bundle exec rake db:setup

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter

cache:
  bundler: true

bundler_args: --without development

addons:
  postgresql: '9.3'
  code_climate:
    repo_token: a6b5c68a72844d9240d79614952ca699370fc356cf9bf4f766095fea4b01e743

notifications:
  email:
    recipients:
      - matheuslazzi@gmail.com
